#ifndef LSLARGEST_EXITCODE_HPP
#define LSLARGEST_EXITCODE_HPP

namespace lsl {

enum class ExitCode {
  SUCCESS = 0,
  NO_ARGS_SPECIFIED,
  ROOT_DOES_NOT_EXIST,
  ROOT_NOT_DIRECTORY,
  ROOT_EMPTY,
  UNKNOWN_OPTION,
  OPTION_VALUE_MISSING,
  BAD_OPTION_VALUE,
  FAILED_TO_OPEN_FILE,
  NOT_ENOUGH_MEMORY
};

} // namespace lsl

#endif // LSLARGEST_EXITCODE_HPP
